### PR TITLE
Added API documentation #378

### PR DESCRIPTION
**Pull request by danecando**
Moved API docs from README.md to API.md following the new [module documentation changes](https://github.com/hapijs/contrib/issues/49)

### CODE REVIEW

**Comment by arb** [comment]
Wow, this looks great! Did you use a script to do it?

**Comment by danecando** [comment]
Thanks! I didn't use any scripts. Just tried to follow suit with some of the other repo's in the ecosystem.

**Comment by arb** [comment]
Ok, if you did it by hand, can you remove the comments in the markdown and also drop the version information? I don't really feel like maintaining that.

**Comment by danecando** [comment]
Sure, no problem. Which comments do you mean though? the <-- --> stuff that wraps the section links?

**Comment by arb** [comment]
Yep. I think you looked at Joi and that uses a script to keep that up to date so that's where those comments come from.

**Comment by danecando** [comment]
Yeah I was comparing a few of the different repo's to get a feel for how it was done. So just to confirm, leave the section links but remove the version and wrapping comments?

**Comment by arb** [comment]
Yeah just have it read "API Reference" and remove all the <-- --> stuff.

**Pull request merged**
