### PR TITLE
Add httpVersion to GreatResponse

### PR DESCRIPTION
**Pull request by hostiphur**
This data is needed when trying to create a custom reporter for the apache combined log format.

### CODE REVIEW

**Comment by arb** [comment]
Did you run `npm test` before opening this pull request?

**Comment by hostiphur** [comment]
I apologize for not getting back to you sooner. I've been very busy the past month. The issue was that I didn't add the new property to the schema in the test. I have added it and everything seems to be in order now.

**Comment by arb** [comment]
Can you please rebase this into a single commit and include the phrase "Closes #410"

**Comment by hostiphur** [comment]
Done and done :)

**Comment by arb** [comment]
Would you be able to make the same change against the v7.0.0 branch here so I don't create a regression?

**Comment by hostiphur** [comment]
Certainly. Forgive me but I'm no git guru. Would I need to make the change manually, or is there some other method I should follow to make this change to v7.0.0?

**Comment by arb** [comment]
Making it manually would be the easiest way considering how much the code has changed.

**Comment by hostiphur** [comment]
OK, that won't be a problem. It's such a minor change anyway.

**Pull request merged**
