### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by achingbrain**
I've got quite a lot of copies of Wreck in my node_modules folder - this means that a lot of logging doesn't occur because Wreck is a singleton.

This PR updates the project dependencies to the latest versions (including Wreck 7).

I hope you'll consider merging this, happy to make whatever amends are necessary.

### CODE REVIEW

**Comment by Marsup** [comment]
We have a no ^ policy in this org.

**Comment by AdriVanHoudt** [comment]
you should keep the x.x.x notation and the new version of hoek does not work on older node versions so your build breaks

**Comment by achingbrain** [comment]
Is it worth still supporting older node versions?  Looks like most of the hapi/* modules are moving to 4+ only.

**Comment by arb** [comment]
As you can see, the build does not pass because this version of good still supports older versions of both hapi and node. I'm not willing to release a breaking change just to update dependencies. The next version (7) of good will include all of these new dependencies and will only support node >= 4.x.x and the corresponding versions of hapi.

As far as the Wreck issue... you can try using npm3 and deduping and see if that helps at all. It is a known issue with Wreck as it is a singleton.

**Comment by achingbrain** [comment]
Fair enough.  Do you know when good 7 will land?

**Comment by arb** [comment]
Nope. Like I tell everyone, if you want to grease the wheels, maybe get your employer to sponsor it? Some details about that [here](https://github.com/hapijs/contrib/blob/master/Sponsorship.md)

**Comment by achingbrain** [comment]
Also fair enough.  Do you have a hit list for things that need doing?  Just update deps and convert everything to ES6 until the tests pass and the linter stops complaining?  Would you accept a PR that does that?

My employer is me so I'm happy to spend some time on this if it helps.

**Comment by arb** [comment]
On any hapi repo, you can just go to issues and look for ones that have a milestone attached to them. In this case - https://github.com/hapijs/good/issues?q=is%3Aopen+is%3Aissue+milestone%3A7.0.0+no%3Aassignee

**Comment by achingbrain** [comment]
Hmm, none of those appear to be 'Update Wreck'.  Indeed, #402 is to remove Wreck logging entirely which I always thought was very useful once you get used to encouraging the owners of modules you depend on to use the same version of Wreck.

**Comment by arb** [comment]
That isn't a realistic solution to the problem. If you wish to continue the discussion, comment on the linked issue.

**Comment by achingbrain** [comment]
Ha, I wasn't suggesting it was, just a reality of trying to get logs out of Wreck consistently :wink: 

Anyway - point taken.

**Pull request closed without merging**
