### PR TITLE
Add request route tags to response event

### PR DESCRIPTION
**Pull request by csabapalfi**
to enable filtering with good-squeeze

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Why not expose `request.route.settings` as a whole?

**Comment by AdriVanHoudt** [comment]
Also the build is failing due to `Line 85: no-trailing-spaces - Trailing spaces not allowed.` ;)

**Comment by csabapalfi** [comment]
Ouch, sorry. 

The reason for exposing tags at the top level because that's how squeeze looks for them: 
https://github.com/hapijs/good-squeeze/blob/master/lib/squeeze.js#L65

**Comment by csabapalfi** [comment]
Also just amended my commit to fix the trailing spaces issue (`npm test` is now looking fine locally). Sorry about that.

**Comment by AdriVanHoudt** [comment]
ah I see then 👍

**Comment by arb** [comment]
Can you update the documentation to include this new field?

**Comment by csabapalfi** [comment]
Sure, added docs for this new field.

**Pull request merged**
