### PR TITLE
Report on wreck requests

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
love this feature!

**Comment by lloydbenson** [comment]
One of the tests is not passing.  I kicked it off again but seems to be consistently failing.  Overall looks good though and a very useful feature!  Thanks Wyatt!

**Comment by lloydbenson** [comment]
Assing this to @arb just to make sure it doesnt conflict with any of the new stuff hes doing to do the final review assuming you get the test working.

**Comment by arb** [comment]
Build is failing.

**Comment by AdriVanHoudt** [comment]
you missed a semicolon ;)
````js
lib/utils.js:
		Line 182: semi - Missing semicolon.
````

**Comment by AdriVanHoudt** [comment]
can't wait for 6.0, thanks @geek for the PR!

**Comment by geek** [comment]
Me either, @arb or @lloydbenson when is 6.0 going to be released!?!

**Pull request merged**
