### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by dan-h-ch**
Created a PR based on comments in this thread.

https://github.com/hapijs/good/issues/527

Hopefully saves someone few hours of searching and getting lucky.

### CODE REVIEW

**Comment by dan-h-ch** [comment]
Yeah, I'm not sure why a change to readme would cause checks to fail. It is possible checks are failing on master?

**Comment by Marsup** [comment]
This doesn't look like a necessary change. It's valid javascript and having `await` in the example already assumes a recent version of node.

**Comment by arb** [comment]
As stated in the linked issue, this is valid and common ES2015 code.

**Comment by dan-h-ch** [comment]
Yes, it's totally valid code but I think a bit confusing to follow as an example.

**Comment by dan-h-ch** [comment]
I'm not saying it's not fair, but I feel like it could be a bit more friendly. While ES2015 should be widely adopted, I think feel like there may be some developers that are not using all the syntactical sugar that it came with.

**Comment by Marsup** [comment]
Then they might learn something.

**Pull request closed without merging**
