### PR TITLE
Handle when request.response is null

### LINKED ISSUE #285: Cannot read property 'statusCode' of null
This error happens on small test server and after a lot of quick page refreshes in browser.

````
TypeError: Cannot read property 'statusCode' of null
    at internals.NetworkMonitor._onResponse (/Users/****/Documents/Projects/***/node_modules/good/lib/network.js:40:38)
    at EventEmitter.emit (events.js:95:17)
    at handler (/Users/****/Documents/Projects/***/node_modules/hapi/node_modules/kilt/lib/index.js:54:44)
    at EventEmitter.emit (events.js:117:20)
    at internals.Request._finalize (/Users/****/Documents/Projects/***/node_modules/hapi/lib/request.js:378:21)
    at internals.Request._reply (/Users/****/Documents/Projects/***/node_modules/hapi/lib/request.js:344:21)
    at /Users/****/Documents/Projects/***/node_modules/hapi/lib/request.js:325:18
    at done (/Users/****/Documents/Projects/***/node_modules/hapi/node_modules/items/lib/index.js:22:21)
    at /Users/****/Documents/Projects/***/node_modules/hapi/lib/request.js:314:24
    at iterate (/Users/****/Documents/Projects/***/node_modules/hapi/node_modules/items/lib/index.js:35:13)
````

### PR DESCRIPTION
**Pull request by chulkilee**
Fixes #285 

It is possible that request.response is null.

I don't know how to add tests for this case :(

### CODE REVIEW

**Comment by arb** [comment]
Like I said on #285, this needs an organic test and a way to show that it works. If the situation won't happen, then we don't need code to cover that hypothetical situation. Perhaps we can get more information on the related issue?

**Comment by chulkilee** [comment]
Left a comment on that issue.

The question is how to test this scenario - I haven't worked much on testing node.js code or hapi internal. So please let me know what would be a good way to test it :)

**Comment by arb** [comment]
This addresses the symptom, but not the actually bug in the code.

**Comment by chulkilee** [comment]
According to hapijs/hapi#2344 request.response can be null, so good should handle such cases.

BTW I rebased the commit to the current master but it is not shown here probably because it's closed PR.

**Comment by arb** [comment]
I can't reopen because of the rebase, if you want to try again, I'll take a look though for sure.

**Pull request closed without merging**
